### ISSUE TITLE
too soon

### ISSUE THREAD

**Issue by hahahahacker2009** [ringwormGO-organization/Docs#1]
We are not any lawyers or license experts. Creating custom license is vulnerable to [effectively] make the project non-free. 
See the [Pine license](https://web.archive.org/web/19970615211946/http://www.washington.edu/pine/overview/legal.html)
they even claim that this license does not allow distribution of modified version.
It is suggested to switch to something like ISC, MIT or BSD.

**Comment by Andrej123456789** [comment]
Hi!
You are free to write a license of your own if you wish, but do keep in mind that 2nd edition of ringwormGO license will come into use after 1st of January 2024. But if you wish you can write your own license and we will use it.

- Stjepan B. M.

**Comment by hahahahacker2009** [comment]
This is a feedback :)

**Comment by hahahahacker2009** [comment]
The flaws of this license (will not mention grammar here):
> If these terms are not followed ringwormGO (and "Outsider" projects) will
contact the project main developer(s).
The right to use the SOFTWARE under the license isn't automatically terminated?
> If you download the source code from a ringwormGO project and that project uses RGL 1.0,
If I obtain a tape/CD copy? I won't have the rights "below"?
> Copying the code is allowed AS LONG as you credit the
> ringwormGO & provide a link to the source code.
How can I credit? (By ensuring a copy of the license appear to all tape/device, or just a note "Copyright YYYY ringwormGO, All right reserved + https://...")
> You are NOT allowed to reditribute the source code,
> unless you have a permision form all of the ringwormGO
> developers.
Effectively make software under the license to be proprietary software. I don't have the right to distribute verbatim copies. While the Pine license only prohibit distribution of modified copies.
> But if a project is archived, for more than 1 year,
> you can redistribute the source code, but you have
> to credit the ringwormGO.
What is archived?
about the "credit", see above.

Don't have to comment about section 2 and 3.

RGL is a proprietary software license.

**Comment by hahahahacker2009** [comment]
The flaws of this license (will not mention grammar here):
> If these terms are not followed ringwormGO (and "Outsider" projects) will
> contact the project main developer(s).

The right to use the SOFTWARE under the license isn't automatically terminated?
> If you download the source code from a ringwormGO project and that project uses RGL 1.0,

If I obtain a tape/CD copy? I won't have the rights "below"?
> Copying the code is allowed AS LONG as you credit the
> ringwormGO & provide a link to the source code.

How can I credit? (By ensuring a copy of the license appear to all tape/device, or just a note "Copyright YYYY ringwormGO, All right reserved + https://...")
> You are NOT allowed to reditribute the source code,
> unless you have a permision form all of the ringwormGO
> developers.

Effectively make software under the license to be proprietary software. I don't have the right to distribute verbatim copies. While the Pine license only prohibit distribution of modified copies.
> But if a project is archived, for more than 1 year,
> you can redistribute the source code, but you have
> to credit the ringwormGO.

What is archived?
about the "credit", see above.

Don't have to comment about section 2 and 3.

RGL is a proprietary software license.

**Comment by Andrej123456789** [comment]
We switched to MIT now
